#!/bin/bash

export system=(
    bluez
    bluez-tools
    cockpit
    cockpit-machines
    cockpit-podman
    cockpit-system
    cockpit-ws
    cups
    dbus
    dbus-daemon
    dbus-tools
    dunst
    fwupd
    flatpak
    git
    gnome-keyring
    gvfs-mtp
    grim
    hyprland
    jmtpfs
    lxpolkit
    man-db
    man-pages
    openssh
    openssl
    papirus-icon-theme
    pipewire
    plocate
    podman
    podman-compose
    polkit
    rofi-wayland
    swaybg
    swayidle
    swaylock
    syncthing
    system-config-printer
    tailscale
    waybar
    wl-clipboard
    wlr-randr
    wireplumber
    xdg-desktop-portal-wlr
    xdg-desktop-portal-hyprland
    xdg-user-dirs
    xorg-x11-server-Xwayland
    zsh
    zsh-autosuggestions
)
export apps=(
    alacritty
    bc
    distrobox
    ffmpeg
    firefox
    hledger
    hledger-web
    htop
    keepassxc
    neovim
    nvtop
    openvpn
    pavucontrol
    playerctl
    ranger
    ripgrep
    steam
    thunar
    thunar-archive-plugin
    thunar-volman
    thunderbird
    unzip
    vlc
    zip
)
export fonts=(
    cascadia-code-fonts
    fontawesome-fonts
    google-noto-emoji-fonts
)
export virtualization=(
    libvirt
    libvirt-daemon-config-network
    libvirt-daemon-kvm
    qemu-kvm
    virt-manager
    libguestfs-tools
    python3-libguestfs
)
export wifi=(
    NetworkManager
    NetworkManager-tui
    NetworkManager-wifi
    atheros-firmware
    b43-fwcutter
    b43-openfwwf
    brcmfmac-firmware
    iwlegacy-firmware
    iwlwifi-dvm-firmware
    iwlwifi-mvm-firmware
    libertas-firmware
    mt7xxx-firmware
    nxpwireless-firmware
    realtek-firmware
    tiwilink-firmware
    atmel-firmware
    zd1211-firmware
)
export all_packages=("${system[@]}" "${apps[@]}" "${fonts[@]}" "${virtualization[@]}" "${wifi[@]}")
