FROM docker.io/archlinux/archlinux:latest

# Enable parallel downloads and multilib
COPY pacman.conf /etc/pacman.conf

RUN pacman -Syu --noconfirm

# Install missing Distrobox dependencies
RUN pacman -S --noconfirm \
    bash-completion \
    bc \
    bzip2 \
    curl \
    diffutils \
    findutils \
    gnupg \
    inetutils \
    iproute \
    iputils \
    keyutils \
    krb5 \
    less \
    lsof \
    man-db \
    man-pages \
    ncurses \
    nss-mdns \
    openssh \
    pam \
    pigz \
    pinentry \
    procps-ng \
    rsync \
    sudo \
    tcpdump \
    time \
    traceroute \
    tree \
    tzdata \
    unzip \
    util-linux \
    wget \
    which \
    whois \
    words \
    xorg-xauth \
    xz \
    zip \
    zsh

# User software
RUN pacman -S --noconfirm \
    discord \
    steam \
    zsh-autosuggestions 

# AUR dependencies
RUN pacman -S --noconfirm \
    base-devel \
    git \
    gtk3 \
    libxss \
    nss \
    ttf-liberation

RUN useradd -m aur-builder && \
    echo "builduser ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/builduser && \
    chmod 0440 /etc/sudoers.d/builduser

USER aur-builder
WORKDIR /home/aur-builder
COPY ./aur-packages.txt /home/aur-builder
COPY ./makepkgs.sh /home/aur-builder
COPY ./installpkgs.sh /home/aur-builder
RUN /home/aur-builder/makepkgs.sh

USER root 
RUN /home/aur-builder/installpkgs.sh
